# Generated by Django 5.1.1 on 2024-09-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('destination_url', models.URLField()),
            ],
        ),
    ]
