# Generated by Django 5.1.1 on 2024-09-08 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='id',
            new_name='hash',
        ),
    ]
