# Generated by Django 5.1.1 on 2024-09-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_rename_id_link_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='hash',
            field=models.CharField(max_length=6),
        ),
    ]
